/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    DataTable: typeof import('./components/DataTable.vue')['default']
    DeleteModal: typeof import('./components/DeleteModal.vue')['default']
    EditModal: typeof import('./components/EditModal.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    ModalEdit: typeof import('./components/ModalEdit.vue')['default']
    NovoUserModal: typeof import('./components/NovoUserModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UsersTable: typeof import('./components/UsersTable.vue')['default']
  }
}
